DPMS fixes
python-xlib/python-xlib pull request #171
Opened 2020-09-11 15:56 UTC by thiagokokada

Closes issue #170.

2020-09-11 15:58 UTC, thiagokokada commented
After merging those fixes @vasily-v-ryabov you can do a release since it is enough for my needs now :+1: .

2020-09-11 16:08 UTC, thiagokokada commented on Xlib/ext/dpms.py
> +    DPMSSetTimeouts(display=self.display,
Maybe it would be a better idea to return the result from this call (that is `None`) so nobody depends on this workaround.

WDYT :thinking: ?

2020-09-11 17:02 UTC, thiagokokada commented
Just wait a little before the review, I will try the suggestion from here: https://github.com/python-xlib/python-xlib/issues/170#issuecomment-691208381

2020-09-11 17:04 UTC, petli requested changes

2020-09-11 17:04 UTC, petli commented on Xlib/ext/dpms.py
> +    info(self)
See my comment in #170: this shouldn't be done by the library code. If a tool doesn't follow the usual event loop model the tool must call `Display.flush()` or `Display.sync()` as necessary to make sure requests have reached the server and been processed.

2020-09-11 17:39 UTC, thiagokokada commented
@petli Calling `Display.sync()` after the functions that do side-effects seems to do the trick.

Can you review again please?

2020-09-12 22:31 UTC, vasily-v-ryabov approved these changes
LGTM

2020-09-14 12:28 UTC, petli approved these changes

2020-09-14 12:29 UTC, merged

2020-09-14 16:47 UTC, thiagokokada commented
Thanks @petli @vasily-v-ryabov :tada: .

@vasily-v-ryabov Can we have a release so I can use those changes in my personal project :thinking: ? If you want, I can write a changelog.